### ISSUE TITLE
Problema con la conexión a postgresql en docker-compose

### ISSUE THREAD

**Issue by GyroElSurfista** [GyroElSurfista/estudiantes-node-express#1]
Tengo el siguiente error al tratar de conectarme con DbSchema a una base de datos postgresql levantada en un contenedor de docker por medio de docker-compose:

```
Connectivity Error
FATAL&#58; la autentificaci�n password fall� para el usuario �postgres1�

DbSchema Advice Check the database settings for (remote) access and the Windows Firewall. Details in 'Tips and Help'.
```

## Archivos
# docker-compose.yml

```
version: '3.8'

services:

  postgres:
    container_name: pg
    image: postgres:16
    env_file:
      - .env
    environment:
      # POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - ${POSTGRES_PORT}:5432
    volumes: 
      - ./config/postgresql.conf:/etc/postgresql.conf
      - /srv/docker/postgresql:/var/lib/postgresql   
      - ./database:/var/lib/postgresql #añadir al gitignore 
    command: postgres -c config_file=/etc/postgresql.conf
    restart: always
```

# .env

```
POSTGRES_USER="usuario_bonito"
POSTGRES_PASSWORD="contraseña_bonita"
POSTGRES_DATABASE="test"
POSTGRES_HOST="localhost"
POSTGRES_PORT="5432"
```

## Evidencias
![image](https://github.com/GyroElSurfista/estudiantes-node-express/assets/81333058/30aacf44-b332-4c5f-a20f-a616c414e0ca)
![image](https://github.com/GyroElSurfista/estudiantes-node-express/assets/81333058/2c3a073a-3947-4f2e-a6b1-89f6f65c7c81)
